/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    application
    id("org.openjfx.javafxplugin") version "0.1.0"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(libs.itextKernel)
    implementation(libs.itextIO)
    implementation(libs.itextSVG)
    implementation(libs.jackson)
    implementation(libs.jacksonDatabind)

    compileOnly(libs.lombok)
    annotationProcessor(libs.lombok)
}

javafx {
    version = "24.0.2"
    modules = listOf("javafx.controls")
}

testing {
    suites {
        val test by getting(JvmTestSuite::class) {
            useJUnitJupiter("5.12.1")
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(24)
    }
}

application {
    mainClass = "org.bingo.ui.Main"
    applicationDefaultJvmArgs = listOf(
        "--enable-native-access=javafx.graphics"
    )
}
