/*
 * This source file was generated by the Gradle 'init' task
 */
package org.bingo;

import org.bingo.generators.BingoCardGenerator;

import java.io.IOException;

public class App {

    public static void main(String[] args) {
        try {
            BingoCardGenerator.generateOnePerPageFormat();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
