/*
 * This source file was generated by the Gradle 'init' task
 */
package org.bingo;

import com.itextpdf.kernel.colors.DeviceRgb;
import org.bingo.services.DocumentBuilder;

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

import org.bingo.model.DocumentConfig;
import org.bingo.model.CardConfig;

public class App {

    public static void main(String[] args) {
        try {

            Path output = Paths.get("output");
            Path resources = Paths.get("resources");
            Path icons = resources.resolve("icons");
            Path header = resources.resolve("Fall_Nature_Bingo_Header.png");
            Path frame = resources.resolve("Fall_Nature_Frame.png");
            Path freeSpace = resources.resolve("Free Space.png");
            Path callingCardHeader = resources.resolve("Fall_Nature_Calling_Cards_Header.png");
            Path token = resources.resolve("Token.png");
            Path instructions = resources.resolve("How To Play.pdf");
            Path font = resources.resolve("Dekko-Regular.ttf");
            Path scissorsIcon = resources.resolve("Scissors.png");
            Path ONE_PER_PAGE_OUTPUT_FILE = output.resolve("FallNature_1PerPage.pdf");
            Path TWO_PER_PAGE_OUTPUT_FILE = output.resolve("FallNature_2PerPage.pdf");
            Path CALLING_CARDS_TOKES_RULES_OUTPUT_FILE = output.resolve(
                    "FallNature_Calling Cards, Tokens, & Rules.pdf"
            );

            DocumentConfig documentConfig = new DocumentConfig(
                    "Fall Nature",
                    icons,
                    header,
                    frame,
                    freeSpace,
                    callingCardHeader,
                    token,
                    instructions,
                    font,
                    scissorsIcon,
                    output,
                    0.25f,
                    0.25f,
                    0.25f,
                    0.25f
            );

            CardConfig bingoCardConfig = new CardConfig(
                    new DeviceRgb(105, 98, 44),
                    new DeviceRgb(113, 51, 29),
                    0.014f,
                    0f,
                    0f,
                    0.5f,
                    0.5f,
                    0.1f,
                    0.5f,
                    0.45f,
                    0.5f,
                    0.45f,
                    0.14f,
                    0.16f,
                    0.05f,
                    0.1f,
                    100,
                    1,
                    ONE_PER_PAGE_OUTPUT_FILE,
                    5,
                    5,
                    true,
                    false
            );

            CardConfig landScapeCardConfig = new CardConfig(
                    new DeviceRgb(105, 98, 44),
                    new DeviceRgb(113, 51, 29),
                    0.014f,
                    0.625f,
                    0.625f,
                    0.35f,
                    0.3f,
                    0.05f,
                    0.3f,
                    0.3f,
                    0.35f,
                    0.3f,
                    0.14f,
                    0.16f,
                    0.05f,
                    0.1f,
                    100,
                    1,
                    TWO_PER_PAGE_OUTPUT_FILE,
                    5,
                    5,
                    true,
                    false
            );

            CardConfig tokensConfig = new CardConfig(
                    new DeviceRgb(0, 0, 0),
                    new DeviceRgb(113, 51, 29),
                    0.014f,
                    0.625f,
                    0.625f,
                    0f,
                    6.8f,
                    0.2f,
                    0f,
                    0f,
                    0f,
                    0f,
                    0.14f,
                    0.16f,
                    0.05f,
                    0.1f,
                    1,
                    1,
                    CALLING_CARDS_TOKES_RULES_OUTPUT_FILE,
                    9,
                    9,
                    true,
                    false
            );

            CardConfig callingCardsConfig = new CardConfig(
                    new DeviceRgb(0, 0, 0),
                    new DeviceRgb(113, 51, 29),
                    0.014f,
                    0f,
                    0f,
                    0f,
                    0f,
                    0.2f,
                    0f,
                    0f,
                    0f,
                    0f,
                    0.14f,
                    0.16f,
                    0.05f,
                    0.1f,
                    1,
                    1,
                    CALLING_CARDS_TOKES_RULES_OUTPUT_FILE,
                    6,
                    5,
                    true,
                    false
            );
            DocumentBuilder.buildOnePerPageBingoCards(documentConfig,bingoCardConfig);
            DocumentBuilder.buildTwoPerPageBingoCards(documentConfig, landScapeCardConfig);
            DocumentBuilder.buildInstructionsTokensCallingCards(documentConfig, tokensConfig, callingCardsConfig);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
